### ISSUE TITLE
cenots 7 run "python bin/sentinel.py" error

### ISSUE THREAD

**Issue by zhangkuicheng** [IoTEChain/Sentinel#1]
just like that 

Python 2.7.5

`# SENTINEL_DEBUG=1 python bin/sentinel.py
2019-05-31 07:49:22 [info]: SCHEMA_VERSION (code) = [20170111-1]
2019-05-31 07:49:22 [info]: DB_SCHEMA_VERSION = [20170111-1]
2019-05-31 07:49:22 An instance of Sentinel is already running -- aborting.
[root@VM_0_14_centos sentinel]# SENTINEL_DEBUG=1 python bin/sentinel.py
2019-05-31 07:49:53 [info]: SCHEMA_VERSION (code) = [20170111-1]
2019-05-31 07:49:53 [info]: DB_SCHEMA_VERSION = [20170111-1]
('SELECT "t1"."id", "t1"."name", "t1"."value", "t1"."created_at", "t1"."updated_at" FROM "settings" AS t1 WHERE ("t1"."name" = ?) LIMIT 1 OFFSET 0', [u'__transient_NEXT_SENTINEL_CHECK_AT'])
2019-05-31 07:49:53 current_time = 1559288993
2019-05-31 07:49:53 next_run_time = 0
2019-05-31 07:49:53 Delay of [9] seconds for cron minute offset
('SELECT "t1"."id", "t1"."name", "t1"."value", "t1"."created_at", "t1"."updated_at" FROM "settings" AS t1 WHERE ("t1"."name" = ?) LIMIT 1 OFFSET 0', [u'__transient_NEXT_SENTINEL_CHECK_AT'])
Traceback (most recent call last):
  File "bin/sentinel.py", line 226, in <module>
    main()
  File "bin/sentinel.py", line 170, in main
    perform_dashd_object_sync(dashd)
  File "bin/sentinel.py", line 24, in perform_dashd_object_sync
    GovernanceObject.sync(dashd)
  File "lib/models.py", line 80, in sync
    golist = dashd.rpc_command('gobject', 'list')
  File "lib/dashd.py", line 44, in rpc_command
    return self.rpc_connection.__getattr__(params[0])(*params[1:])
  File "/usr/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 141, in __call__
    raise JSONRPCException(response['error'])
bitcoinrpc.authproxy.JSONRPCException: -1: gobject "command"...
Manage governance objects

Available commands:
  check              - Validate governance object data (proposal only)
  prepare            - Prepare governance object by signing and creating tx
  submit             - Submit governance object to network
  deserialize        - Deserialize governance object from hex string to JSON
  count              - Count governance objects and votes (additional param: 'json' or 'all', default: 'json')
  get                - Get governance object by hash
  getvotes           - Get all votes for a governance object hash (including old votes)
  getcurrentvotes    - Get only current (tallying) votes for a governance object hash (does not include old votes)
  list               - List governance objects (can be filtered by signal and/or object type)
  diff               - List differences since last diff
  vote-alias         - Vote on a governance object by masternode alias (using masternode.conf setup)
  vote-conf          - Vote on a governance object by masternode configured in iote.conf
  vote-many          - Vote on a governance object by all masternodes (using masternode.conf setup)

('SELECT "t1"."id", "t1"."name", "t1"."value", "t1"."created_at", "t1"."updated_at" FROM "settings" AS t1 WHERE ("t1"."name" = ?) LIMIT 1 OFFSET 0', [u'__transient_SENTINEL_RUNNING'])
('DELETE FROM "settings" WHERE ("id" = ?)', [2])
`

please help me solve it

**Comment by ohash-ai** [comment]
@zhangkuicheng 
hello ~
I also encountered the same problem. Have you solved it?
